spring:
  application:
    name: adventurebook
  datasource:
    url: jdbc:h2:mem:adventurebook
  jpa:
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true

#temporary, for verification only
logging:
  level:
    org.hibernate.SQL: debug
