spring:
  application:
    name: adventurebook
  datasource:
    url: jdbc:h2:mem:adventurebook
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          batch_size: 50
        order_inserts: true
        order_updates: true
  h2:
    console:
      enabled: true
